### ISSUE TITLE
Get room name and member names with this SDK

### ISSUE THREAD

**Issue by MardorZ** [baking-bad/matrix-dotnet-sdk#10]
Hi!

What is the expected way of dealing with display names in this SDK? 
Everything works fine but i am missing the names of rooms and users and can only find ids.
In the .js SDK i got room names and member names after initial sync.

**Comment by SlimeQ** [comment]
Just want to note that both of these functions are available in my PR https://github.com/baking-bad/matrix-dotnet-sdk/pull/11
