### ISSUE TITLE
[help] Can't receive a message 

### ISSUE THREAD

**Issue by zblesk** [baking-bad/matrix-dotnet-sdk#2]
Hello! 

I like this API, but I'm having issues receiving messages - not sure if I'm doing something wrong, or if it isn't implemented yet. 
I used client credentials for a user that was already set up - joined in the rooms I need it in. 

Most of the process works - I can log in and send a message into a room. (I didn't call Join. It's a public room the user was already in and I just provided the ID.) 
However, when I send a message to that room (from a different user, logged in via Element) the `OnMatrixRoomEventsReceived` callback is never called. (I'm using the one from the sample.)

I did try calling the `JoinTrustedPrivateRoomAsync` with that ID (the room is public, but I see no other join method). It threw no error, but it also didn't change anything.  
Is this possible?
Thank you!

**Comment by iviich4eL** [comment]
Hello! 

Sorry for late response. 

To start listening events you should do this https://github.com/baking-bad/matrix-dotnet-sdk/blob/56b38ce56b6322d97431d6788caa6d5202409a59/Matrix.Sdk.Sample.Console/SimpleExample.cs#L85

This call will initialize message polling

**Comment by pro-anon** [comment]
I'm having the same issues. The client can send a message, so `LoginAsync` and `SendMessageAsync` both work fine. But I don't receive any events at all, and no exceptions are thrown. Also the number of joined rooms is always 0, whether I join public or private rooms.

![image](https://user-images.githubusercontent.com/97809837/149679483-c8d27500-2d76-4eba-9a25-148bf2b35c85.png)

I found out that I can pass a logger to the client's constructor, and this is what I got:
`fail: Matrix.Sdk.Core.Domain.Services.PollingService[0]
      Exception`
I sent a message to a room that I had already joined using the web app, it was sent successfully and this hash was the response.
After sending the message, I joined a room that I invited myself to using a different account `client.JoinTrustedPrivateRoomAsync(roomId);`
It joined successfully, but when I logged the `room.Status`, it showed `Unknown`. Afterwards, it logs the room id. Then it shows this `info` thing with the same joined room's id.

**Comment by ShaadiAlfred** [comment]
![image](https://user-images.githubusercontent.com/3685582/149679061-c4897de6-3318-4a5f-bc46-5d607971540c.png)

I found out that I can pass a logger to the client's constructor, and this is what I got:
`fail: Matrix.Sdk.Core.Domain.Services.PollingService[0]
      Exception`
I sent a message to a room that I had already joined using the web app, it was sent successfully and this hash was the response.
After sending the message, I joined a room that I invited myself to using a different account `client.JoinTrustedPrivateRoomAsync("!JfmwXYpQAgILkBIvMg:matrix.org");`
It joined successfully, but when I logged the `room.Status`, it showed `Unknown`. Afterwards, it logs the room id. Then it shows this `info` thing of the with the same joined room id.

**Comment by iviich4eL** [comment]
Hello, @pro-anon 

Could you please provide some code snippets for your issue?

You can also try to run a complete sample - https://github.com/baking-bad/matrix-dotnet-sdk/blob/main/Matrix.Sdk.Sample.Console/SimpleExample.cs. 
(Clone this repository and run Matrix.Sdk.Sample.Console project)

Does sync work in this case?

**Comment by iviich4eL** [comment]
Hello, @zblesk

Could you please provide some code snippets for your issue?

**Comment by pro-anon** [comment]
@iviich4eL 
`SimpleExample.cs`
```csharp
public async Task Run()
{
    SystemConsoleTheme theme = LoggerSetup.SetupTheme();
    Log.Logger = new LoggerConfiguration()
        .Enrich.FromLogContext()
        .WriteTo.Console(theme: theme)
        .CreateLogger();

    var factory = new MatrixClientFactory();

    IMatrixClient client = factory.Create();

    client.OnMatrixRoomEventsReceived += (sender, eventArgs) =>
    {
        System.Console.WriteLine("Something happened");
        foreach (BaseRoomEvent roomEvent in eventArgs.MatrixRoomEvents)
        {
            if (roomEvent is not TextMessageEvent textMessageEvent)
                continue;

            (string roomId, string senderUserId, string message) = textMessageEvent;
            if (client.UserId != senderUserId)
                Console.WriteLine($"RoomId: {roomId} received message from {senderUserId}: {message}.");
        }
    };

    (Uri matrixNodeAddress, string username, string password, string deviceId) = CreateLoginRequest();
    await client.LoginAsync(matrixNodeAddress, username, password, deviceId);

    client.Start();

    await client.SendMessageAsync("<room-id>:matrix.org", "Hello");

    Console.WriteLine($"client.IsLoggedIn: {client.IsLoggedIn}");
    Console.WriteLine($"client.IsSyncing: {client.IsSyncing}");

    // await client.GetJoinedRoomsIdsAsync();
    // string roomId = string.Empty;
    // await client.LeaveRoomAsync(roomId);

    Console.ReadLine();

    client.Stop();

    Console.WriteLine($"client.IsLoggedIn: {client.IsLoggedIn}");
    Console.WriteLine($"client.IsSyncing: {client.IsSyncing}");
}

private static LoginRequest CreateLoginRequest()
{
    var baseAddress = new Uri("https://matrix.org/");

    LoginRequest loginRequest = new LoginRequest(
        baseAddress,
        "<username>",
        "<password>",
        "BOT"
    );

    return loginRequest;
}
```
I hard coded my credentials to try the `Matrix.Sdk.Sample.Console` out. The same thing happens however. Messages are successfully sent, but no event is caught. When I send a message in a room, which the account already joined, from other accounts, no events are triggered at all.

**Comment by iviich4eL** [comment]
Hello!

Matrix.Sdk was updated to v0.0.7. This release fixes the issue with an `OnMatrixRoomEventsReceived` callback. 

@zblesk, @pro-anon, if you experience any issues, please, let me know

**Comment by zblesk** [comment]
Sorry, that was a long time ago. I'm not using this library anymore and don't have the code, either, so I won't be able to provide feedback. Thank you anyway!

**Comment by Miepee** [comment]
I think I'm having this issue as well.
I first tried to do a very simple bot by using the steps from the readme, where the code did look something like this:
```cs
var factory = new MatrixClientFactory();
IMatrixClient client = factory.Create();
await client.LoginAsync(Credentials.HomeServer, Credentials.UserName, Credentials.Password, "Bot");

client.OnMatrixRoomEventsReceived += (sender, eventArgs) =>
{
    foreach (BaseRoomEvent roomEvent in eventArgs.MatrixRoomEvents)
    {
        if (roomEvent is not TextMessageEvent textMessageEvent)
            continue;

        (string roomId, string senderUserId, string message) = textMessageEvent;
        if (client.UserId != senderUserId)
            Console.WriteLine($"RoomId: {roomId} received message from {senderUserId}: {message}.");
    }
};

client.Start();

await Task.Delay(-1);

```

However, the OnMatrixRoomEventsReceived never fired. Thinking I might've done something wrong, i just used the sample project, where I replaced `await client.LoginAsync(matrixNodeAddress, username, password, deviceId);` with `await client.LoginAsync(Credentials.HomeServer, Credentials.UserName, Credentials.Password, "Bot");`. But that then resulted in me getting a bunch of ApiExceptions:
```
Matrix.Sdk.ApiException: Matrix API error. Status: Unauthorized, json: {"errcode":"M_UNKNOWN_TOKEN","error":"Invalid macaroon passed.","soft_logout":false}
   at Matrix.Sdk.Core.Infrastructure.Extensions.HttpClientExtensions.PostAsJsonAsync[TResponse](HttpClient httpClient, String requestUri, Object model, CancellationToken cancellationToken)
   at Matrix.Sdk.Core.Infrastructure.Services.RoomService.JoinRoomAsync(String accessToken, String roomId, CancellationToken cancellationToken)
   at Matrix.Sdk.MatrixClient.JoinTrustedPrivateRoomAsync(String roomId)
   at MatrixTest.DependencyInjectionSample.Run(IServiceProvider serviceProvider) in C:\Users\me\source\repos\MatrixTest\MatrixTest\DependencyInjectionSample.cs:line 94
   at MatrixTest.Program.Main(String[] args) in C:\Users\me\source\repos\MatrixTest\MatrixTest\Program.cs:line 25
   at MatrixTest.Program.<Main>(String[] args)
```
(DependencyInjectionSample was slightly changed, the actual lines are these: 
https://github.com/baking-bad/matrix-dotnet-sdk/blob/main/Matrix.Sdk.Sample.Console/DependencyInjectionSample.cs#L78-L83)

I also noticed that `client.JoinedRooms` is completely empty, which probably is the reason why on my small test example the event never fired.

If I'm doing anything wrong, I'd love to know.
