### ISSUE TITLE
Clarifications regarding limited API support

### ISSUE THREAD

**Issue by kimimaru4000** [baking-bad/matrix-dotnet-sdk#6]
Hi! First off, thanks for this project! I've been looking for a newer Matrix .NET SDK to use in [TRBot](https://codeberg.org/kimimaru/TRBot) to allow people to play games by chatting in Matrix rooms.

The README says that this SDK has support for a limited subset of the Matrix API at present. Are there plans to support all of the API in time? No pressure here - just asking!

As-is, does this library allow reading chats from a specific Matrix room? Does this room have to be unencrypted, or is there also support for E2E encryption?

Thank you very much!

**Comment by m-kus** [comment]
Hey!
We do not plan to add new features in the near future, but we welcome any kind of contribution :)
Current implementation allows to join specific unencrypted rooms and subscribe to their events.
