### ISSUE TITLE
New fork

### ISSUE THREAD

**Issue by squidink7** [baking-bad/matrix-dotnet-sdk#8]
Hello, and thank you for making this awesome library!

I was looking for a C# implementation of the matrix sdk to use in my projects, however I wanted one that worked with .NET 7 and its new Native AOT feature. I wanted to be able to compile my bot into a small native library that could be called from other languages through FFI, which meant I needed to find a library that could function without reflection. Taking a look at this I determined that the use of Newtonsoft.Json caused me to be unable to use AOT compilation, so I created a fork and refactored this project to rely on System.Text.Json using source generators. My forked project is available here: https://codeberg.org/nullbyte/matrix-sdk, and if any of these changes are of interest I would be happy to open a pull request to merge them upstream. (it's worth noting, however, that I had to update the target framework to net7 in order to use AOT, and I haven't tested with netstandard)
I also altered the nullability of certain properties to remove warnings when building, which fixed #7.

Thank you for your time, and best wishes with future development.

**Comment by m-kus** [comment]
Hey! Sorry for lag and thank you for the feedback :)
I think there are no blockers for replacing json library, but there might be issues with net7 support in the dependent software.
But we should certainly fix #7, @k-karuna can you please look into?

**Comment by squidink7** [comment]
net7 isn't a requirement for my changes afaik, I just used that version for it's aot support in my project. That being said I've heard System.Text.Json isn't built in to older .net frameworks, and I don't have a windows machine to test on.

**Comment by k-karuna** [comment]
@squidink7 closing this due to last time activity. If you have any suggestions feel free to open new PR's / issues.
